// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Photo struct {
	ID          string  `json:"id"`
	URL         string  `json:"url"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
}
